# Generated by Django 5.2.5 on 2025-08-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoodBadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MoneySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/money/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.badblock')),
            ],
        ),
        migrations.AddField(
            model_name='badblock',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.goodbadsection'),
        ),
        migrations.CreateModel(
            name='GoodBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_icon', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.goodbadsection')),
            ],
        ),
        migrations.CreateModel(
            name='GoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.goodblock')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.moneysection')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/professions/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.subject')),
            ],
        ),
        migrations.AddField(
            model_name='moneysection',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession'),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='profession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professions.profession'),
        ),
        migrations.CreateModel(
            name='ProfessionAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/profession_abilities/')),
                ('subtitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionAbilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/profession_abilities_icons/')),
                ('text', models.CharField(max_length=255)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professionability')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/professions_details/')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/profession_blocks/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='WhereWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('video', models.FileField(upload_to='media/videos')),
                ('video_text', models.TextField(blank=True, null=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/logos/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.whereworks')),
            ],
        ),
    ]
