# Generated by Django 5.2.5 on 2025-08-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professioncategory')),
            ],
        ),
        migrations.AlterField(
            model_name='profession',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professioncategory'),
        ),
    ]
