# Generated by Django 5.2.5 on 2025-08-25 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_professioncategory_alter_profession_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professions.professioncategory'),
        ),
    ]
