# Generated by Django 5.2.5 on 2025-08-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0003_alter_professioncategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='name',
        ),
    ]
