# Generated by Django 5.2.5 on 2025-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0004_remove_profession_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='subjects',
        ),
        migrations.AddField(
            model_name='profession',
            name='subjects',
            field=models.ManyToManyField(to='professions.subject'),
        ),
    ]
