# Generated by Django 5.2.5 on 2025-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0005_remove_profession_subjects_profession_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyitem',
            name='text',
        ),
        migrations.AddField(
            model_name='moneyitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
