# Generated by Django 5.2.5 on 2025-08-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0006_remove_moneyitem_text_moneyitem_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneysection',
            name='profession',
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='high',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='low',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='middle',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MoneyItem',
        ),
        migrations.DeleteModel(
            name='MoneySection',
        ),
    ]
