# Generated by Django 5.2.5 on 2025-08-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BadBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FutureDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kelajakni hozirdan quring', max_length=255, verbose_name="Bo'lim sarlavhasi")),
                ('child_profession', models.CharField(max_length=255, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='future/', verbose_name='Rasm')),
            ],
        ),
        migrations.CreateModel(
            name='GoodBadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='IntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Intro Section',
                'verbose_name_plural': 'Intro Sections',
            },
        ),
        migrations.CreateModel(
            name='LandingResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='landing_resume/')),
                ('button_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoneySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='money/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='professions/main/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaxsiy_text', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('letter', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('button_text', models.CharField(default='Saqlash', max_length=50)),
                ('old_password', models.CharField(blank=True, max_length=128, null=True)),
                ('new_password', models.CharField(blank=True, max_length=128, null=True)),
                ('password_button_text', models.CharField(default='Parolni yangilash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Kichik sarlavha')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description_title', models.CharField(max_length=255, verbose_name='Asosiy sarlavha')),
                ('description', models.TextField(verbose_name='Izoh / Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/', verbose_name='Rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('letter', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('password_repeat', models.CharField(max_length=128)),
                ('button_text', models.CharField(default='Kirish', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='resume_pictures/')),
                ('text', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Batafsil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview', models.ImageField(upload_to='resumes/templates/')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/templates/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('content_uz', models.TextField(null=True, verbose_name='Kontent')),
                ('content_ru', models.TextField(null=True, verbose_name='Kontent')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='starter/', verbose_name='Rasm')),
            ],
        ),
        migrations.CreateModel(
            name='StepSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='test_about/')),
                ('notification_icon', models.ImageField(blank=True, null=True, upload_to='test_about/notifications/')),
                ('notification_title', models.CharField(blank=True, max_length=255)),
                ('notification_text', models.TextField(blank=True)),
                ('button_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='training/videos/')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='about_pictures/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.about')),
            ],
        ),
        migrations.CreateModel(
            name='BadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.badblock')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='main.contact')),
            ],
        ),
        migrations.AddField(
            model_name='badblock',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_blocks', to='main.goodbadsection'),
        ),
        migrations.CreateModel(
            name='GoodBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_icon', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_blocks', to='main.goodbadsection')),
            ],
        ),
        migrations.CreateModel(
            name='GoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.goodblock')),
            ],
        ),
        migrations.CreateModel(
            name='IntroButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='main.introsection')),
            ],
        ),
        migrations.CreateModel(
            name='IntroText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='main.introsection')),
            ],
        ),
        migrations.CreateModel(
            name='LandingResumeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='landing_resume/icons/')),
                ('text', models.TextField()),
                ('landing_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.landingresume')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.moneysection')),
            ],
        ),
        migrations.AddField(
            model_name='moneysection',
            name='profession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='money', to='main.profession'),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='profession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='good_bad', to='main.profession'),
        ),
        migrations.CreateModel(
            name='ProfessionAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profession/abilities/')),
                ('label', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='main.profession')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='category',
            field=models.ManyToManyField(related_name='professions', to='main.professioncategory'),
        ),
        migrations.CreateModel(
            name='ProfessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='professions/details/')),
                ('profession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.profession')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='profession_icons/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.professiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikonka (class yoki emoji)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='main.projectsection')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaxsiy_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shablon_text', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='resumes/photos/')),
                ('jins', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='main.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.CharField(choices=[('native', 'Ona tili'), ('english', 'Ingliz tili'), ('other', 'Boshqa til')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='main.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_finish', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('school_class', models.CharField(blank=True, max_length=50, null=True)),
                ('letter', models.CharField(blank=True, max_length=10, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='main.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=200)),
                ('profession_category', models.CharField(max_length=200)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='main.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeStepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='resume_steps/icons/')),
                ('text', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.resumestep')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='step_icons/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.stepsection')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='subjects',
            field=models.ManyToManyField(related_name='professions', to='main.subject'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('is_correct', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('interest_text', models.TextField(blank=True, null=True)),
                ('ability_text', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.test')),
            ],
        ),
        migrations.CreateModel(
            name='InterestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='interests/')),
                ('text', models.CharField(max_length=255)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='main.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='abilities/')),
                ('text', models.CharField(max_length=255)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='main.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', 'Oddiy rang'), ('chernobely', 'Oq-qora')], default='default', max_length=20)),
                ('font_size', models.CharField(choices=[('1x', 'Normal'), ('1.5x', 'Kattaroq'), ('2x', 'Juda katta')], default='1x', max_length=10)),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский')], default='uz', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhereWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_text', models.TextField(blank=True, null=True)),
                ('profession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='where_works', to='main.profession')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.BooleanField(default=False)),
                ('work_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('when', models.CharField(blank=True, max_length=100, null=True)),
                ('work_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('about_work', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='main.resume')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='main.whereworks')),
            ],
        ),
    ]
