# Generated by Django 5.2.5 on 2025-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ability_name_ru_ability_name_uz_abilityitem_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='picture/abilities/'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='picture',
            field=models.ImageField(upload_to='picture/about_pictures/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture/answers/'),
        ),
        migrations.AlterField(
            model_name='futuredream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture/future/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='interestitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='picture/interests/'),
        ),
        migrations.AlterField(
            model_name='landingresume',
            name='picture',
            field=models.ImageField(upload_to='picture/landing_resume/'),
        ),
        migrations.AlterField(
            model_name='landingresumeblock',
            name='icon',
            field=models.ImageField(upload_to='picture/landing_resume/icons/'),
        ),
        migrations.AlterField(
            model_name='moneysection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture/money/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/resumes/photos/'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture/professions/main/'),
        ),
        migrations.AlterField(
            model_name='professionability',
            name='picture',
            field=models.ImageField(upload_to='picture/profession/abilities/'),
        ),
        migrations.AlterField(
            model_name='professionabilityitem',
            name='icon',
            field=models.ImageField(upload_to='picture/profession/abilities/icons/'),
        ),
        migrations.AlterField(
            model_name='professionblock',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='picture/profession_icons/'),
        ),
        migrations.AlterField(
            model_name='professiondetail',
            name='image',
            field=models.ImageField(upload_to='picture/professions/details/'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture/project/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='resumeinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/resume_pictures/'),
        ),
        migrations.AlterField(
            model_name='resumestepitem',
            name='icon',
            field=models.ImageField(upload_to='picture/resume_steps/icons/'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='picture/resumes/templates/files/'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='preview',
            field=models.ImageField(upload_to='picture/resumes/templates/'),
        ),
        migrations.AlterField(
            model_name='starter',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/starter/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='stepitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='picture/step_icons/'),
        ),
        migrations.AlterField(
            model_name='testabout',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/test_about/'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5),
        ),
        migrations.AlterField(
            model_name='worklogo',
            name='logo',
            field=models.ImageField(upload_to='picture/logos/'),
        ),
    ]
