# Generated by Django 5.2.5 on 2025-08-25 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='media/landing_resume/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaxsiy_text', models.CharField(default="Shaxsiy ma'lumotim", max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('letter', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('old_password', models.CharField(blank=True, max_length=128, null=True)),
                ('new_password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('letter', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('password_repeat', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Professional rezume bu:', max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/resume_info')),
                ('text', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview', models.ImageField(upload_to='media/resume_templates/')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/resume_template_files/')),
            ],
        ),
        migrations.CreateModel(
            name='LandingResumeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='media/landing_resume_icons/')),
                ('text', models.TextField()),
                ('landing_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.landingresume')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaxsiy_text', models.CharField(default='Shaxsiy', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shablon_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('picture', models.ImageField(upload_to='media/resume_photos/')),
                ('jins', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type1', models.CharField(choices=[('native', 'Ona tili'), ('english', 'Ingliz tili'), ('other', 'Boshqa til')], max_length=20)),
                ('language_type2', models.CharField(choices=[('native', 'Ona tili'), ('english', 'Ingliz tili'), ('other', 'Boshqa til')], max_length=20)),
                ('language_type3', models.CharField(choices=[('native', 'Ona tili'), ('english', 'Ingliz tili'), ('other', 'Boshqa til')], max_length=20)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_finish', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('school_class', models.CharField(max_length=50)),
                ('letter', models.CharField(max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=200)),
                ('profession_category', models.CharField(max_length=200)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeStepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='picture/resume_steps/icons/')),
                ('text', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resumestep')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', 'Oddiy rang'), ('chernobely', 'Oq-qora')], default='default', max_length=20)),
                ('font_size', models.CharField(choices=[('1x', 'Normal'), ('1.5x', 'Kattaroq'), ('2x', 'Juda katta')], default='1x', max_length=10)),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.BooleanField(default=False)),
                ('work_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('when', models.CharField(blank=True, max_length=100, null=True)),
                ('work_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('about_work', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
    ]
