# Generated by Django 5.2.5 on 2025-08-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='shaxsiy_text',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='resume',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='users.resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='users.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='users.resume'),
        ),
        migrations.AlterField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='users.resume'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.resume'),
        ),
    ]
