# Generated by Django 5.2.5 on 2025-08-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_resume_shaxsiy_text_resumetemplate_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/resume_photos/'),
        ),
    ]
