# Generated by Django 5.2.5 on 2025-08-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abilityitem',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abilityitem',
            name='text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='baditem',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='baditem',
            name='text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='profession_category_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='profession_category_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='profession_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='profession_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='city_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='city_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='letter_ru',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='letter_uz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='region_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='region_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_class_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_class_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='futuredream',
            name='child_profession_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='futuredream',
            name='child_profession_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='futuredream',
            name='title_ru',
            field=models.CharField(default='Kelajakni hozirdan quring', max_length=255, null=True, verbose_name="Bo'lim sarlavhasi"),
        ),
        migrations.AddField(
            model_name='futuredream',
            name='title_uz',
            field=models.CharField(default='Kelajakni hozirdan quring', max_length=255, null=True, verbose_name="Bo'lim sarlavhasi"),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gooditem',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gooditem',
            name='text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interestitem',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interestitem',
            name='text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introbutton',
            name='text_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='introbutton',
            name='text_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='introsection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='introsection',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='introsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introsection',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introtext',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='introtext',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='button_text_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='button_text_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingresumeblock',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresumeblock',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresumeblock',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingresumeblock',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moneyblock',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moneyblock',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moneyblock',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moneyblock',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moneysection',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moneysection',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moneysection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moneysection',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='label_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='label_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionblock',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionblock',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionblock',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionblock',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professioncategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professioncategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_text_ru',
            field=models.CharField(default='Saqlash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_text_uz',
            field=models.CharField(default='Saqlash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='class_name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='class_name_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='letter_ru',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='letter_uz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_button_text_ru',
            field=models.CharField(default='Parolni yangilash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_button_text_uz',
            field=models.CharField(default='Parolni yangilash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shaxsiy_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shaxsiy_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Izoh / Matn'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Izoh / Matn'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='subtitle_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='register',
            name='button_text_ru',
            field=models.CharField(default='Kirish', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='button_text_uz',
            field=models.CharField(default='Kirish', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='city_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='class_name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='class_name_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='letter_ru',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='letter_uz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='region_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='region_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='school_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='school_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='shablon_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='shablon_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='shaxsiy_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='shaxsiy_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='button_text_ru',
            field=models.CharField(default='Batafsil', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='button_text_uz',
            field=models.CharField(default='Batafsil', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumestep',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumestep',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumestep',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumestep',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumestepitem',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumestepitem',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumestepitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumestepitem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stepitem',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stepitem',
            name='text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stepsection',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepsection',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stepsection',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='button_text_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='notification_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='notification_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='notification_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='notification_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='ability_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='ability_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='interest_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='interest_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingcomment',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingcomment',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='video_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='video_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='about_work_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='about_work_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='profession_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='profession_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='when_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='when_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_duration_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_duration_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_name_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ProfessionAbilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='profession/abilities/icons/')),
                ('text', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255, null=True)),
                ('text_ru', models.CharField(max_length=255, null=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.professionability')),
            ],
        ),
    ]
