# Generated by Django 5.2.5 on 2025-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_abilityitem_icon_alter_aboutimage_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abilityitem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='baditem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='profession_category_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='profession_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='city_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='letter_en',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='region_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_class_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='futuredream',
            name='child_profession_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='futuredream',
            name='title_en',
            field=models.CharField(default='Kelajakni hozirdan quring', max_length=255, null=True, verbose_name="Bo'lim sarlavhasi"),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goodbadsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gooditem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interestitem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introbutton',
            name='text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='introsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='introsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introtext',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='button_text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresume',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingresumeblock',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingresumeblock',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moneyblock',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moneyblock',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moneysection',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moneysection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='label_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionability',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionabilityitem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionblock',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionblock',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professioncategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professiondetail',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_text_en',
            field=models.CharField(default='Saqlash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='class_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='letter_en',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_button_text_en',
            field=models.CharField(default='Parolni yangilash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shaxsiy_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Izoh / Matn'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='register',
            name='button_text_en',
            field=models.CharField(default='Kirish', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='class_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='letter_en',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='region_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='school_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='shablon_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='shaxsiy_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='button_text_en',
            field=models.CharField(default='Batafsil', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumestep',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumestep',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumestepitem',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumestepitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='starter',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='stepitem',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stepsection',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='notification_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='notification_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testabout',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='ability_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='interest_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingcomment',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whereworks',
            name='video_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='about_work_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='profession_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='when_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_duration_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
