# Generated by Django 5.2.5 on 2025-08-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ability_name_en_abilityitem_text_en_about_text_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Starter',
        ),
        migrations.AlterModelOptions(
            name='introsection',
            options={},
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='title_uz',
        ),
    ]
